# -*- coding: utf-8 -*-
"""7thSemProject.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JlXNNk1gHhlwXa1R-OZSswLfqRIDtfOg
"""

import requests
from bs4 import BeautifulSoup
import smtplib

pip install requests

url="https://www.amazon.in/Reno3-Auroral-128GB-Storage-Without/dp/B07X8V5YLP/ref=asc_df_B07X8V5YLP/?tag=googleshopdes-21&linkCode=df0&hvadid=426450193604&hvpos=&hvnetw=g&hvrand=13059559850660625216&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9040199&hvtargid=pla-915723891074&psc=1&ext_vrnc=hi"

headers={"user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36"}

page=requests.get(url,headers=headers)

soup=BeautifulSoup(page.content,'html.parser')

print(soup.prettify())

print(soup.title) #title of the page

print(soup.title.name)

print(soup.title.string)

print(soup.title.parent.name)

print(soup.p) #for getting specific values

print(soup.find_all('p'))

for paragraph in soup.find_all('p'):
     print(paragraph.string)
     print(str(paragraph.text))

for url in soup.find_all('a'):
  print(url.get('href'))

a = soup.find(id="productTitle")
b=a.get_text()

print(b.strip())

price = soup.find( id="priceblock_ourprice")
price.get_text()

cp = price.get_text()
s = cp[2:8]
type(s)
str
cp[1]

c=23990.0 #amazon

res=requests.get("https://www.flipkart.com/oppo-reno3-pro-auroral-blue-128-gb/p/itm05804cb14fc19?pid=MOBFPYA4RSKUJZPH&lid=LSTMOBFPYA4RSKUJZPHJHMMX4&marketplace=FLIPKART&srno=s_1_1&otracker=search&otracker1=search&fm=SEARCH&iid=946ef5fc-1659-439a-9330-1fc8ef992b52.MOBFPYA4RSKUJZPH.SEARCH&ppt=pp&ppn=pp&ssid=642yh79ak00000001614425472113&qH=58c1b3757e044017")

soup=BeautifulSoup(res.text,"html")

name = soup.select("._1AtVbE")

price = soup.select("._30jeq3._16Jk6d")

price

d=24879 #flipkart

price = 0
company=""
if c<d:
  price=c
  company="Flipkart"
else:
    price=d
    company="Amazon"

print(price)
print(company)

def send_mail():
  server=smtplib.SMTP("smtp.gmail.com",587)
  server.ehlo()
  server.starttls()
  server.ehlo()
  server.login("LilyyMist@gmail.com","Lilyy_MIST1320")
  subject="price fell down"
  if company == "FlipKart" :
    body = "check the Flipkart link : https://www.flipkart.com/oppo-reno3-pro-auroral-blue-128-gb/p/itm05804cb14fc19?pid=MOBFPYA4RSKUJZPH&lid=LSTMOBFPYA4RSKUJZPHJHMMX4&marketplace=FLIPKART&srno=s_1_1&otracker=search&otracker1=search&fm=SEARCH&iid=946ef5fc-1659-439a-9330-1fc8ef992b52.MOBFPYA4RSKUJZPH.SEARCH&ppt=pp&ppn=pp&ssid=642yh79ak00000001614425472113&qH=58c1b3757e044017"
    msg=f"Subject:{subject}\n\n{body}"
    server.sendmail(
        "swastikabarua38@gmail.com",
        msg
    )

    print("HEY!! email has been sent")
    server.quit()

  else:
   body = "check the Amazon link : https://www.amazon.in/Reno3-Auroral-128GB-Storage-Without/dp/B07X8V5YLP/ref=asc_df_B07X8V5YLP/?tag=googleshopdes-21&linkCode=df0&hvadid=426450193604&hvpos=&hvnetw=g&hvrand=13059559850660625216&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9040199&hvtargid=pla-915723891074&psc=1&ext_vrnc=hi"
   msg=f"Subject:{subject}\n\n{body}"
   server.sendmail(
        "swastikabarua38@gmail.com",
        msg
        )

print("HEY! email has been sent")
server_quit()

send_mail()